//! v1 feature extraction — the Rust mirror of `flow_ml.features`.
//!
//! Training (Python) and live inference (Rust) must compute *identical*
//! features: a silent divergence here would skew every probability the
//! model outputs, with no error anywhere. The two implementations are
//! therefore pinned by a parity test (`tests/feature_parity.rs`) against
//! fixtures generated by `flow_ml.export` — same contract discipline as
//! the ONNX bridge (ADR 0004).
//!
//! Everything is computed in `f64`, like the Python side; the model input
//! is converted to `f32` at the very end. The mean pairwise correlation
//! mirrors numpy's conventions exactly: constant subcarriers contribute
//! zero (their correlation is undefined), and coefficients are clamped to
//! `[-1, 1]`.

use std::borrow::Borrow;

use flow_core::CsiFrame;
use thiserror::Error;

/// Per-node feature names, in vector order — must match
/// `flow_ml.features.NODE_FEATURES`.
pub const NODE_FEATURES: [&str; 7] = [
    "amp_mean",
    "amp_std",
    "motion_energy",
    "subcarrier_corr",
    "rssi_mean",
    "rssi_std",
    "frame_rate",
];

/// Below this, temporal statistics are meaningless — must match
/// `flow_ml.features.MIN_FRAMES_PER_NODE`.
pub const MIN_FRAMES_PER_NODE: usize = 2;

/// Failure to compute features over a window.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Error)]
pub enum FeatureError {
    /// Not enough frames for temporal statistics.
    #[error("need at least {MIN_FRAMES_PER_NODE} frames, got {got}")]
    TooFewFrames {
        /// Number of frames provided.
        got: usize,
    },
    /// Frames within one window disagree on the subcarrier count.
    #[error("inconsistent subcarrier counts within the window")]
    InconsistentSubcarriers,
    /// Frames carry no subcarrier data.
    #[error("frames carry no subcarrier data")]
    NoSubcarriers,
    /// The window duration is zero.
    #[error("window duration must be positive")]
    ZeroDuration,
}

/// Feature vector for one node's frames within one window.
///
/// `frames` must share one subcarrier count and hold at least
/// [`MIN_FRAMES_PER_NODE`] entries; `duration_us` is the window length.
///
/// # Errors
///
/// See [`FeatureError`].
pub fn node_features<F: Borrow<CsiFrame>>(
    frames: &[F],
    duration_us: u64,
) -> Result<[f64; 7], FeatureError> {
    if frames.len() < MIN_FRAMES_PER_NODE {
        return Err(FeatureError::TooFewFrames { got: frames.len() });
    }
    if duration_us == 0 {
        return Err(FeatureError::ZeroDuration);
    }
    let width = frames[0].borrow().amp.len();
    if width == 0 {
        return Err(FeatureError::NoSubcarriers);
    }
    if frames.iter().any(|f| f.borrow().amp.len() != width) {
        return Err(FeatureError::InconsistentSubcarriers);
    }
    let count = frames.len();
    let count_f = count as f64;
    let width_f = width as f64;

    // Per-subcarrier temporal means.
    let mut means = vec![0.0f64; width];
    for frame in frames {
        for (mean, amp) in means.iter_mut().zip(&frame.borrow().amp) {
            *mean += f64::from(*amp);
        }
    }
    for mean in &mut means {
        *mean /= count_f;
    }
    let amp_mean = means.iter().sum::<f64>() / width_f;

    // Per-subcarrier population standard deviation.
    let mut variances = vec![0.0f64; width];
    for frame in frames {
        for (variance, (amp, mean)) in variances
            .iter_mut()
            .zip(frame.borrow().amp.iter().zip(&means))
        {
            let centered = f64::from(*amp) - mean;
            *variance += centered * centered;
        }
    }
    for variance in &mut variances {
        *variance /= count_f;
    }
    let stds: Vec<f64> = variances.iter().map(|v| v.sqrt()).collect();
    let amp_std = stds.iter().sum::<f64>() / width_f;

    // Motion energy: mean absolute frame-to-frame amplitude change.
    let mut motion = 0.0f64;
    for pair in frames.windows(2) {
        let (previous, current) = (pair[0].borrow(), pair[1].borrow());
        for (a, b) in previous.amp.iter().zip(&current.amp) {
            motion += (f64::from(*b) - f64::from(*a)).abs();
        }
    }
    let motion_energy = motion / (((count - 1) * width) as f64);

    // Mean pairwise Pearson correlation between subcarrier series.
    let subcarrier_corr = if width < 2 {
        0.0
    } else {
        let mut off_diagonal = 0.0f64;
        for i in 0..width {
            for j in (i + 1)..width {
                if stds[i] > 0.0 && stds[j] > 0.0 {
                    let mut covariance = 0.0f64;
                    for frame in frames {
                        let amp = &frame.borrow().amp;
                        covariance +=
                            (f64::from(amp[i]) - means[i]) * (f64::from(amp[j]) - means[j]);
                    }
                    covariance /= count_f;
                    off_diagonal += (covariance / (stds[i] * stds[j])).clamp(-1.0, 1.0);
                }
            }
        }
        2.0 * off_diagonal / (width_f * width_f - width_f)
    };

    let rssi_mean = frames
        .iter()
        .map(|f| f64::from(f.borrow().rssi))
        .sum::<f64>()
        / count_f;
    let rssi_std = (frames
        .iter()
        .map(|f| {
            let centered = f64::from(f.borrow().rssi) - rssi_mean;
            centered * centered
        })
        .sum::<f64>()
        / count_f)
        .sqrt();

    let frame_rate = count_f / (duration_us as f64 / 1e6);

    Ok([
        amp_mean,
        amp_std,
        motion_energy,
        subcarrier_corr,
        rssi_mean,
        rssi_std,
        frame_rate,
    ])
}

/// Concatenated per-node features for one window's frames.
///
/// `rx_nodes` must be the session's receiving nodes in stable (sorted)
/// order — the column order the model was trained with. Returns
/// `Ok(None)` when any node lacks enough frames in the window (an
/// incomplete observation, dropped rather than half-filled), mirroring
/// `flow_ml.features.window_vector`.
///
/// # Errors
///
/// See [`FeatureError`].
pub fn window_vector(
    frames: &[CsiFrame],
    rx_nodes: &[String],
    duration_us: u64,
) -> Result<Option<Vec<f64>>, FeatureError> {
    let mut out = Vec::with_capacity(rx_nodes.len() * NODE_FEATURES.len());
    for node_id in rx_nodes {
        let node_frames: Vec<&CsiFrame> = frames.iter().filter(|f| &f.node_id == node_id).collect();
        if node_frames.len() < MIN_FRAMES_PER_NODE {
            return Ok(None);
        }
        out.extend(node_features(&node_frames, duration_us)?);
    }
    Ok(Some(out))
}

#[cfg(test)]
mod tests {
    use super::*;

    const SECOND: u64 = 1_000_000;
    const EPS: f64 = 1e-12;

    fn frame(ts_us: u64, amp: Vec<f32>, node_id: &str) -> CsiFrame {
        let phase = vec![0.0; amp.len()];
        CsiFrame::new(ts_us, node_id, -52, 7, amp, phase).unwrap()
    }

    #[test]
    fn constant_signal_has_zero_agitation() {
        // Mirror of flow_ml test_constant_signal_has_zero_agitation.
        let frames: Vec<CsiFrame> = (0..3)
            .map(|t| frame(t * SECOND, vec![2.0, 2.0], "rx-1"))
            .collect();
        let vector = node_features(&frames, 3 * SECOND).unwrap();
        let expected = [2.0, 0.0, 0.0, 0.0, -52.0, 0.0, 1.0];
        for (index, (got, want)) in vector.iter().zip(&expected).enumerate() {
            assert!(
                (got - want).abs() < EPS,
                "{}: got {got}, want {want}",
                NODE_FEATURES[index]
            );
        }
    }

    #[test]
    fn linear_ramp_matches_hand_computation() {
        // Mirror of flow_ml test_linear_ramp_features_match_hand_computation.
        let frames: Vec<CsiFrame> = (0..3)
            .map(|t| frame(t * SECOND, vec![t as f32, t as f32], "rx-1"))
            .collect();
        let vector = node_features(&frames, 3 * SECOND).unwrap();
        assert!((vector[0] - 1.0).abs() < EPS, "amp_mean");
        assert!((vector[1] - (2.0f64 / 3.0).sqrt()).abs() < EPS, "amp_std");
        assert!((vector[2] - 1.0).abs() < EPS, "motion_energy");
        assert!((vector[3] - 1.0).abs() < EPS, "subcarrier_corr");
    }

    #[test]
    fn rejects_degenerate_inputs() {
        let one = vec![frame(0, vec![1.0, 2.0], "rx-1")];
        assert_eq!(
            node_features(&one, SECOND),
            Err(FeatureError::TooFewFrames { got: 1 })
        );

        let mixed = vec![
            frame(0, vec![1.0, 2.0], "rx-1"),
            frame(1, vec![1.0, 2.0, 3.0], "rx-1"),
        ];
        assert_eq!(
            node_features(&mixed, SECOND),
            Err(FeatureError::InconsistentSubcarriers)
        );

        let two = vec![
            frame(0, vec![1.0, 2.0], "rx-1"),
            frame(1, vec![1.0, 2.0], "rx-1"),
        ];
        assert_eq!(node_features(&two, 0), Err(FeatureError::ZeroDuration));
    }

    #[test]
    fn window_vector_concatenates_in_node_order() {
        let mut frames = Vec::new();
        for t in 0..3 {
            frames.push(frame(t * SECOND, vec![2.0, 2.0], "rx-1"));
            frames.push(frame(t * SECOND, vec![5.0, 5.0], "rx-2"));
        }
        let nodes = vec!["rx-1".to_owned(), "rx-2".to_owned()];
        let vector = window_vector(&frames, &nodes, 3 * SECOND).unwrap().unwrap();
        assert_eq!(vector.len(), 2 * NODE_FEATURES.len());
        assert!((vector[0] - 2.0).abs() < EPS, "rx-1 amp_mean first");
        assert!(
            (vector[NODE_FEATURES.len()] - 5.0).abs() < EPS,
            "rx-2 amp_mean second"
        );
    }

    #[test]
    fn window_vector_is_none_when_a_node_is_missing() {
        let frames: Vec<CsiFrame> = (0..3)
            .map(|t| frame(t * SECOND, vec![2.0, 2.0], "rx-1"))
            .collect();
        let nodes = vec!["rx-1".to_owned(), "rx-2".to_owned()];
        assert_eq!(window_vector(&frames, &nodes, 3 * SECOND), Ok(None));
    }
}
