//! Density inference for the Mariam Flow edge.
//!
//! Implemented: loading and execution of the ONNX density classifier with
//! `tract` ([`DensityModel`]), producing per-class probabilities with
//! derived class, confidence, and expected density level ([`Prediction`]).
//! The Python↔Rust parity contract (ADR 0004) is enforced by the
//! integration test in `tests/parity.rs` against fixtures generated by
//! `flow_ml.export`.
//!
//! Implemented as well: the wait-time layer ([`WaitEstimator`]) —
//! Little's Law over the expected people count, time-aware exponential
//! smoothing, display-class hysteresis, and confidence gating.
//!
//! Planned: integration into the live edge daemon. See
//! `docs/architecture.md`.

#![forbid(unsafe_code)]
#![warn(missing_docs)]

mod model;
mod wait;

pub use model::{DensityModel, InferError, Prediction};
pub use wait::{
    ClassHysteresis, ConfigError, Ema, WaitConfig, WaitEstimate, WaitEstimator, expected_people,
};
