//! Density inference for the Mariam Flow edge.
//!
//! Implemented: loading and execution of the ONNX density classifier with
//! `tract` ([`DensityModel`]), producing per-class probabilities with
//! derived class, confidence, and expected density level ([`Prediction`]).
//! The Python↔Rust parity contract (ADR 0004) is enforced by the
//! integration test in `tests/parity.rs` against fixtures generated by
//! `flow_ml.export`.
//!
//! Planned: Little's Law wait-time estimation and output smoothing
//! (EMA + hysteresis). See `docs/architecture.md`.

#![forbid(unsafe_code)]
#![warn(missing_docs)]

mod model;

pub use model::{DensityModel, InferError, Prediction};
