//! Feature parity test: the Rust extraction must reproduce the Python
//! reference (`flow_ml.features`) that the model was trained with.
//!
//! Fixtures are generated by `flow_ml.export` alongside the ONNX parity
//! fixtures: `cd ml && uv run python -m flow_ml.export
//! ../crates/flow-infer/tests/fixtures`

use std::fs;
use std::path::PathBuf;

use flow_core::CsiFrame;
use flow_infer::{NODE_FEATURES, node_features};
use serde::Deserialize;

#[derive(Deserialize)]
struct Fixture {
    tolerance: f64,
    features: Vec<String>,
    cases: Vec<Case>,
}

#[derive(Deserialize)]
struct Case {
    duration_us: u64,
    frames: Vec<CsiFrame>,
    expected: Vec<f64>,
}

fn load_fixture() -> Fixture {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/features.json");
    serde_json::from_str(&fs::read_to_string(path).unwrap()).unwrap()
}

#[test]
fn feature_names_match_the_python_reference() {
    let fixture = load_fixture();
    assert_eq!(fixture.features, NODE_FEATURES);
}

#[test]
fn rust_features_reproduce_the_python_reference() {
    let fixture = load_fixture();
    assert!(!fixture.cases.is_empty());

    let mut worst: f64 = 0.0;
    for (index, case) in fixture.cases.iter().enumerate() {
        for frame in &case.frames {
            frame.validate().unwrap();
        }
        let vector = node_features(&case.frames, case.duration_us).unwrap();
        assert_eq!(vector.len(), case.expected.len(), "case {index}");
        for (got, want) in vector.iter().zip(&case.expected) {
            worst = worst.max((got - want).abs());
        }
    }
    assert!(
        worst <= fixture.tolerance,
        "feature parity violated: max |Δ| = {worst:e}, tolerance = {:e}",
        fixture.tolerance
    );
}
